

# Setup
title:                <p style = "font-family:candara, arial,helvetica;"> Farhad Shirani<br>
tagline:              <font color=#8E8E8C>Research Assistant Professor<br>
                     fsc265@nyu.edu</font></p>
description:         <img src="/public/favicon4-apple.png">
url:                 http://lanyon.getpoole.com
baseurl:             ''
paginate:            5

# About/contact
author:
  name:             Farhad Shirani
  email:            fsc265@nyu.edu

# Custom vars
version:             1.0.0
